name: Backup database
description: Back up the database on the remote windows server
inputs:
  server:
    description: 'server ip'
    required: true
  account:
    description: 'server account'
    required: false
    default: 'Administrator'
  password:
    description: 'server password'
    required: true
  name:
    description: 'database name'
    required: true
  path:
    description: 'backup file path'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
